sudo: false
language: ruby
cache: bundler

branches:
  only:
    master

matrix:
  include:
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

script: bundle exec rake
