sudo: false
language: ruby
cache: bundler

branches:
  only:
    master

matrix:
  include:
    - rvm: 2.2.8
    - rvm: 2.3.5
    - rvm: 2.4.2
    - rvm: ruby-head
  allow_failures:
    - rvm: 2.4.2
    - rvm: ruby-head

script: bundle exec rake
